import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/components/provider/AppProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Roboto } from "next/font/google";
import AuthProvider from "@/components/provider/AuthProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "TechStar Dashboard",
  description: "Generated by TechStar Dashboard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <AuthProvider>
          <AppProvider>
            {children} <ToastContainer position="top-right" />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
